In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_excel('/content/drive/My Drive/FolderBaru/K-nn/Tabel Latihan Knn.xlsx')
df

  handphone  kamera  berat  tebal  layak
0        H1      16    165    8.5     Ya
1        H2      13    165    8.6  Tidak
2        H3      13    180    9.0     Ya
3        H4       8    164    8.4  Tidak
4        H5      13    165    8.5     Ya
5        H6       5    167    8.6  Tidak
6        H7       7    165    8.5     Ya

In [71]:
atribut = df.columns[1:-1]
target = df.columns[-1]

In [72]:
input = {
    'kamera':{'nilai':10,'bobot':0.9},
    'berat':{'nilai':163,'bobot':0.1},
    'tebal':{'nilai':8.7,'bobot':0.1}
}

In [73]:
def Euclidean_distance(df,attribute,input,bobot=1):
  bantu = 0
  for i in attribute:
    bantu += (df[i]-input[i])**2
    df['Euclidean_distance'] = bantu**0.5
  return df['Euclidean_distance']

In [74]:
bantu = 0
bobot = 1
for i in atribut:
  try:
    bobot = input[i]['bobot']
  except:
    bobot = 1
  bantu += bobot * (df[i]-input[i]['nilai'])**2
  df['Euclidean_distance'] = bantu**0.5

In [75]:
df

  handphone  kamera  berat  tebal  layak  Euclidean_distance
0        H1      16    165    8.5     Ya            5.727478
1        H2      13    165    8.6  Tidak            2.915647
2        H3      13    180    9.0     Ya            6.083502
3        H4       8    164    8.4  Tidak            1.925876
4        H5      13    165    8.5     Ya            2.916162
5        H6       5    167    8.6  Tidak            4.909277
6        H7       7    165    8.5     Ya            2.916162

In [19]:
Euclidean_distance(df,atribut,input)

0     6.327717
1     3.606938
2    17.265283
3     2.256103
4     3.611094
5     6.403905
6     3.611094
Name: Euclidean_distance, dtype: float64

In [20]:
df

  handphone  kamera  berat  tebal  layak  Euclidean_distance
0        H1      16    165    8.5     Ya            6.327717
1        H2      13    165    8.6  Tidak            3.606938
2        H3      13    180    9.0     Ya           17.265283
3        H4       8    164    8.4  Tidak            2.256103
4        H5      13    165    8.5     Ya            3.611094
5        H6       5    167    8.6  Tidak            6.403905
6        H7       7    165    8.5     Ya            3.611094

In [37]:
df = df.sort_values(by='Euclidean_distance').reset_index(drop=True)
df

  handphone  kamera  berat  tebal  layak  Euclidean_distance
0        H4       8    164    8.4  Tidak            2.256103
1        H2      13    165    8.6  Tidak            3.606938
2        H5      13    165    8.5     Ya            3.611094
3        H7       7    165    8.5     Ya            3.611094
4        H1      16    165    8.5     Ya            6.327717
5        H6       5    167    8.6  Tidak            6.403905
6        H3      13    180    9.0     Ya           17.265283

In [90]:
k = int((len(df)/2)**0.5)
k = 3

In [91]:
df['masuk_kategori'] = None
for i in range(len(df)):
  if i < k:
    df['masuk_kategori'][i] = True
  else:
    df['masuk_kategori'][i] = False

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [98]:
prediksi = df.groupby(['masuk_kategori','layak'])['layak'].count()

In [99]:
prediksi

masuk_kategori  layak
False           Tidak    2
                Ya       2
True            Tidak    1
                Ya       2
Name: layak, dtype: int64

In [89]:
df

  handphone  kamera  berat  tebal  layak  Euclidean_distance masuk_kategori
0        H1      16    165    8.5     Ya            3.847597           True
1        H2      13    165    8.6  Tidak            6.670907          False
2        H3      13    180    9.0     Ya            8.544530          False
3        H4       8    164    8.4  Tidak           11.388986          False
4        H5      13    165    8.5     Ya            6.671132          False
5        H6       5    167    8.6  Tidak           14.286392          False
6        H7       7    165    8.5     Ya           12.349251          False

In [123]:
def knn(df,attribute,target,input,k):
  bantu = 0
  for i in attribute:
    try:
      bobot = input[i]['bobot']
    except:
      bobot = 1
    try:
      bantu += bobot * (df[i]-input[i]['nilai'])**2
    except:
      bantu += bobot * (df[i]-input[i])**2
    df['Euclidean_distance'] = bantu**0.5
  df = df.sort_values(by='Euclidean_distance').reset_index(drop=True)
  df['masuk_kategori'] = None
  for i in range(len(df)):
    if i < k:
      df['masuk_kategori'][i] = True
    else:
      df['masuk_kategori'][i] = False
  prediksi = df.groupby(['masuk_kategori',target])[target].count()
  return prediksi[True]

In [115]:
knn(df,atribut,target,input,5)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

layak
Tidak    3
Ya       2
Name: layak, dtype: int64

In [116]:
input2 = {
    'kamera':{'nilai':20,'bobot':0.9},
    'berat':{'nilai':163,'bobot':0.1},
    'tebal':{'nilai':8.7,'bobot':0.1}
}

In [117]:
knn(df,atribut,target,input2,1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

layak
Ya    1
Name: layak, dtype: int64

In [118]:
df2 = pd.read_excel('/content/drive/My Drive/FolderBaru/K-nn/Tabel Knn-2.xlsx')
df2

   daya_tahan_asam  kekuatan klasifikasi
0                8         4        Baik
1                4         5       Jelek
2                4         6       Jelek
3                7         7        Baik
4                5         6       Jelek
5                6         5        Baik

In [119]:
input3 = {
    'daya_tahan_asam':7,
    'kekuatan':4
}

In [122]:
df2.columns[-1]

'klasifikasi'

In [124]:
knn(df2,df2.columns[:-1],df2.columns[-1],input3,3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

klasifikasi
Baik     2
Jelek    1
Name: klasifikasi, dtype: int64